export const HERO_CONTENT_ANIMATION_DURATION = 0.8;
export const PHONE_FRAME_TRANSLATE_ANIMATION_DURATION = 0.8;
export const PHONE_CONTENT_ANIMATION_DELAY = PHONE_FRAME_TRANSLATE_ANIMATION_DURATION + 0.2;
